version: '3.8'
services:
    db:
        image: 'sdabizljevic3920rn/database:1.0'
        container_name: db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
        restart: unless-stopped
        networks:
            - backend-network
    
    redis:
        image: 'redis:latest'
        container_name: rdb
        ports:
            - "6379:6379"
        restart: unless-stopped
        networks:
            - backend-network
    
    user-service:
        image: vzivanovic/user-service:4.0
        ports:
            - "8080:8080"
        container_name: user-service 
        restart: unless-stopped
        networks:
            - backend-network

    banka-service:
        image: vzivanovic/banka-service:4.0
        ports:
            - "8082:8082"
        container_name: banka-service 
        restart: unless-stopped
        networks:
            - backend-network
    
    berza-service:
        image: vzivanovic/berza-service:4.0
        ports:
            - "8081:8081"
        container_name: berza-service
        restart: unless-stopped
        networks:
            - backend-network    
networks:
    backend-network:
        driver: bridge
